### ISSUE TITLE
Select Time Endpoint + Postgres

### ISSUE THREAD

**Issue by dnmct** [devhausleipzigacademy/camp12-midterm-backend#18]
## Expected Behaviour

When a user selects a date create an api endpoint that checks available times

## Checklist

_Detail the steps below to help us reproduce the problem you encountered._

- [x] create check-times endpoint
- [x] the endpoint should return an array of availbale timeslots
- [x] a timeslot is not available if all the seats are booked

## Hints
- Booked seats are stored as a comma seperated string (e.g. "A1,A2")
- You need to transform that into and array to check the length

**Comment by Fredmpk** [comment]
got replaxced by new isue 25
