### ISSUE TITLE
Bookmarks route - GET

### ISSUE THREAD

**Issue by dnmct** [devhausleipzigacademy/camp12-midterm-backend#20]
## Expected Behaviour

we need an endpoint that gives us all the bookmarks for a given user

## Checklist

_Detail the steps below to help us reproduce the problem you encountered._

- [x] Hook up endpoint with the database
- [x] read the bookmarks for a specific user by using a join
- [x] send back array of bookmarked ids

**Comment by nakropin** [comment]
Now implemented with prisma
