### ISSUE TITLE
Reservation Route

### ISSUE THREAD

**Issue by dnmct** [devhausleipzigacademy/camp12-midterm-backend#29]
Create a route that can make a reservation

- id
- screeningId
- userId
- movieId
- date
- time
- seats

- [x] Create a post route that takes all the fields above except id (this should be autogenerated)
- [ ] Validate the request.body with a zod schema
- [ ] return the created reservation

**Comment by Hydrateurself** [comment]
schema screening,
zod check body valid reservation
check if user id is actual user
check if screening exists
